### ISSUE TITLE
PLL clock is incorrectly limited to 24MHz on l0x3 devices

### ISSUE THREAD

**Issue by akashihi** [stm32-rs/stm32l0xx-hal#110]
PLL clock is limited here https://github.com/stm32-rs/stm32l0xx-hal/blob/master/src/rcc.rs#L307 to 24MHz, but l073 supports up to 32MHz.

**Comment by nebelgrau77** [comment]
L031 is affected as well, it also supports 32 MHz.

**Comment by akashihi** [comment]
I checked [L0 series selector](https://www.st.com/en/microcontrollers-microprocessors/stm32l0-series.html) and found that _all_ STM32L0 mcus actually support 32MHz.
