### ISSUE TITLE
stm32l0x3 support

### ISSUE THREAD

**Issue by tkeksa** [stm32-rs/stm32l0xx-hal#15]
Are you going to implement stm32l0x3 support?

**Comment by arkorobotics** [comment]
There are no plans to implement support at this time, but it's not to say it won't happen. I think most folks are adding to the project based on their MCU of choice. 

As always, PR's to add support are always welcome.

**Comment by tkeksa** [comment]
Thanks for your honest answer.
It is time to dive into embedded Rust and STM32 deeper.

**Comment by arkorobotics** [comment]
Sounds good :)

I'm going to close this issue. If you find yourself struggling to add support for the x3, you can always open an issue with an enhancement label to request the added feature.
