### ISSUE TITLE
Clippy CI build fails

### ISSUE THREAD

**Issue by hannobraun** [stm32-rs/stm32l0xx-hal#163]
The Clippy CI build currently fails, presumably because a new Clippy version has been pulled in. It would be nice to get this fixed (either by following what Clippy says or by silencing those warnings; haven't looked into it, so don't know what would be appropriate). Any pull request doing so would be very welcome!

**Comment by hannobraun** [comment]
Here's a failing build: https://github.com/stm32-rs/stm32l0xx-hal/runs/2296253088?check_suite_focus=true

**Comment by dbrgn** [comment]
Regarding the non-uppercase identifiers: I'd suggest silencing these warnings since acronyms are used a lot. Simply applying the fixes might break third party code without any gain.

I'll give it a try.
