### ISSUE TITLE
Incorrect AHB prescaler calculation

### ISSUE THREAD

**Issue by knoellle** [stm32-rs/stm32l0xx-hal#225]
I think the AHB prescaler divisors are not correctly calculated.
The enum kinds [here](https://github.com/stm32-rs/stm32l0xx-hal/blob/master/src/rcc.rs#L80-L90) are mapped to four bits which are then used to left-shift the divisor in [here](https://github.com/stm32-rs/stm32l0xx-hal/blob/master/src/rcc.rs#L419-L422).
However, there's a gap in the divisors, there is no Div32, but the bits-to-divisor calculation does not handle this gap.
This means, that when a prescaler of 64 or higher is used, the reported frequency is too high by a factor of 2.

**Comment by dbrgn** [comment]
Without checking the datasheet: I think you're right, good catch. Would you be willing to submit a pull request with a fix?
