### ISSUE TITLE
docs.rs failed to build stm32l0xx-hal-0.3.0

### ISSUE THREAD

**Issue by tkeksa** [stm32-rs/stm32l0xx-hal#34]
See https://docs.rs/crate/stm32l0xx-hal/0.3.0/builds/182532
The problem seems to be custom build.rs which requires exactly one feature enabled but there is:
```
[package.metadata.docs.rs]
features = ["stm32l0x1", "stm32l0x2", "stm32l0x3", "rt"]
```
Probably either just one feature should be enabled for docs build (as it has e.g. stm32f1xx_hal) or custom build.rs should be disabled for docs somehow.

**Comment by arkorobotics** [comment]
Thanks for the ticket! This issue has been resolved. Please see docs.rs for version [0.3.1](https://docs.rs/crate/stm32l0xx-hal/0.3.1/).
