### ISSUE TITLE
EXTI API is partially broken, could use an update

### ISSUE THREAD

**Issue by hannobraun** [stm32-rs/stm32l0xx-hal#42]
I've been planning to update the EXTI API for a while now, as I believe that it has started to outgrow its initial design. I started working on that, but it turns out I bit off more than I can chew.

I'm pausing this work until I can come up with some new ideas. In the meantime, I'm opening this issue to document the current shortcomings of the API, and the problems I had coming up with a better design.

Here's what's wrong with EXTI, as I see it:
- The API is partially broken. Some of its methods rely on bit-banding, but everything I read says that bit-banding is only supported on Cortex-M3/M4. I couldn't find any evidence that STM32L0 is an exception.
- The API is focused on configurable interrupt lines, more specifically GPIO interrupts. Direct interrupt lines aren't really considered. This means that a user has to pass all kinds of arguments that aren't actually needed.

In essence, there are three kind of interrupt lines:
- Direct lines, which can only be enabled/disabled.
- Configurable lines, which can be configured to trigger on rising and/or falling edges.
- GPIO lines, which are configurable lines that also need special handling in SYSCFG, as all GPIO pins are multiplexed onto 16 EXTI lines.

The challenge I had was coming up with a design that:
1. Doesn't require the user to pass arguments that are not actually used for a given interrupt line. That isn't just inconvenient but also error-prone, as it can easily lead to misunderstandings.
2. Doesn't duplicate code all over the place.
3. Does 1. and 2. without becoming super-complicated.

I'll think about this in the back of my mind for a while before I give this another go. If anyone has any ideas in the meantime, feel free to comment.

**Comment by jonas-schievink** [comment]
(working on this now)
