### ISSUE TITLE
Supplying a customized memory map?

### ISSUE THREAD

**Issue by l29ah** [stm32-rs/stm32l0xx-hal#84]
I want to make a bootloader and a chain-loaded firmware, so i need to specify my own memory map. However, if i try to do it via `link-arg=-Tfoo.x`, i'm promptly told that `rust-lld: error: foo.x:3: region 'FLASH' already defined`. How can i override the supplied memory map?

**Comment by dbrgn** [comment]
I think you can use the `disable-linker-script` feature. Does that work?

https://github.com/stm32-rs/stm32l0xx-hal/blob/f3b3e824252abfe6e5a592f3ce850d47d56cd112/build.rs#L28

**Comment by l29ah** [comment]
Oh, yes, thank you!
